resources:
  - name: myaws
    type: cliConfig
    integration: myaws
    pointer:
      region: us-east-1

jobs:
  - name: windows_job
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    steps:
      - IN: myaws
      - TASK:
          name: hello_world
          runtime:
            options:
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
            - screenfetch
            - shipctl retry docker foo
            - shipctl retry docker ps
            - shipctl get_resource_name foobar-1-2-3-4
