resources:
  - name: pl_repo
    type: gitRepo
    integration: github
    versionTemplate:
      sourceName: skylark05/pipelines
      branch: master
      
  - name: myaws
    type: cliConfig
    integration: myaws
    pointer:
      region: us-east-1
  - name: img
    type: image
    integration: myDH
    pointer:
      sourceName: ragesh/busybox
    seed:
      versionName: master.1
      

jobs:
  - name: windows_job
    type: runSh
    runtime:
      nodePool: custom__x86_64__WindowsServer_2016
      container: false
    steps:
      - IN: myaws
      - IN: pl_repo
      - TASK:
          name: hello_world
          runtime:
            options:
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
            #- '"versionName=master.$env:BUILD_NUMBER" | Out-File -Encoding utf8 -FilePath $env:JOB_STATE\img.env -NoNewLine'
            #- shipctl post_resource_state "img" "versionName" "master.$env:BUILD_NUMBER"
            - shipctl get_resource_version_key "pl_repo" "shaData"
            - start-sleep -m 2
      - OUT: img
        overwrite: true
  - name: windows_container_job
    type: runSh
    runtime:
      nodePool: custom__x86_64__WindowsServer_2016
      container: true
    steps:
      - TASK:
          name: hello_container_world
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
