resources:
  - name: myaws
    type: cliConfig
    integration: myaws
    pointer:
      region: us-east-1
  - name: img
    type: image
    integration: myDH
    pointer:
      sourceName: ragesh/busybox
    seed:
      versionName: master.1
      

jobs:
  - name: windows_job
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: false
    steps:
      - IN: myaws
      - TASK:
          name: hello_world
          runtime:
            options:
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
            - screenfetch
            - shipctl retry docker foo
            - shipctl retry docker ps
            - shipctl get_resource_name foobar-1-2-3-4
            - aws ec2 describe-instances
            - '"versionName=master.$env:BUILD_NUMBER" | Out-File -Encoding utf8 -FilePath $env:JOB_STATE\img.env -NoNewLine'
            - shipctl post_resource_state img versionName ${env:BRANCH}.${env:BUILD_NUMBER}
      - OUT: img
        overwrite: true
  - name: windows_container_job
    type: runSh
    runtime:
      architecture: x86_64
      os: WindowsServer_2016
      container: true
    steps:
      - TASK:
          name: hello_container_world
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
