language: none
runtime:
  nodePool: custom__x86_64__WindowsServer_2016
build:
  ci:
    - echo "Hello World"

resources:
  #- name: pl_repo
  #  type: gitRepo
  #  integration: github
  #  versionTemplate:
  #    sourceName: skylark05/pipelines
  #    branch: master
      
  #- name: myaws
  #  type: cliConfig
  #  integration: myaws
  #  pointer:
  #    region: us-east-1
  #- name: img
  #  type: image
  #  integration: myDH
  #  pointer:
  #    sourceName: ragesh/busybox
  #  seed:
  #    versionName: master.1
      

jobs:
  - name: test_dynamic_win
    type: runSh
    allowPublicAccess: true
    runtime:
      container: false
    steps:
      - TASK:
          name: hello_world
          script:
            - Write-Output "Hello"
  - name: windows_job
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: dynamic__x86_64__WindowsServer_2016__c4_large
      container: false
    steps:
      #- IN: myaws
      #- IN: pl_repo
      #- IN: shippable_windows_master
      #  switch: off
      - TASK:
          name: hello_world
          runtime:
            options:
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
            #- pushd $(shipctl get_resource_state pl_repo)
            #- git status
            #- popd
            #- pushd $(shipctl get_resource_state shippable_windows_master)
            #- git status
            #- popd
      - OUT: img
        overwrite: true
  - name: windows_container_job
    type: runSh
    runtime:
      nodePool: dynamic__x86_64__WindowsServer_2016__c4_large
      container: true
    steps:
      - TASK:
          name: hello_container_world
          runtime:
            options:
              imageName: "microsoft/windowsservercore"
              imageTag: "10.0.14393.1884"
              env:
                HELLO: world
          script:
            - Write-Output "Greetings from Windows on Shippable"
